
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })
import styles from '../styles/layoutRoot.module.css'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const links = [
  
  { id: 1, url: './coordenadas/cartesianas', text: 'Cartesianas' },
  { id: 2, url: './coordenadas/esfericas', text: 'Esféricas' },
  { id: 3, url: './coordenadas/Polares', text: 'Polares' },
  { id: 4, url: './coordenadas/cilindricas', text: 'Cilíndricas' },
  
  
];


export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={styles.body}>
        <header className={styles.header}>
          <a href='/'>
          <h1>
            Coordenadas
          </h1>
          </a>
       

        <Navbar  links={links}/>
        </header>
       
        {children}
      </body>
    </html>
  )
}
